# Simple Gradient Descent Demo

# 1. Importing data

In [1]:
import pandas as pd
import numpy as np


In [2]:
sample_data_df = pd.read_csv(r"F:\Data Science Grand Track\Machine Learning\datasets\SampleDataGE.csv")
display(sample_data_df)

Size (sq. m)  No. rooms  Age (yrs)   Price
0            102          4          2  190257
1             67          4         29  216410
2             74          2         27  132887
3             63          4          1  197341
4            114          3         12  127647
5            109          5          9  225818
6             73          3         21  336404
7            108          4         24  324823
8             69          2         29  313475
9             81          4         11  144088
10            60          5          9  182709
11            62          5         32  221915
12            87          4         19  343853
13            61          5         15  142479
14            62          4          9  253968
15            69          5         21  326047
16           119          2         24  261348
17           101          3         21  137322
18            76          4         20  195267
19            91          4          7  249774
20            75          4         19  242577

# 2. Setup hyperparameters

## Setup learning rate, theta (bias + weight) matrix

In [ ]:
# Learning rate
lr_rate = 0.0001

# Theta array [b w_1 w_2 w_3]
theta = np.zeros(3)

# Number of epoch
epochs = 10

# Print theta, learning_rate, epoch count:
print(lr_rate)
print(theta)
print(epochs)



0.0001
[0. 0. 0. 0.]
10


## Setup feature matrix

In [19]:
# Feature vectors
X = sample_data_df[['Size (sq. m)','No. rooms', 'Age (yrs)']]
print(X)

# Features 
y = sample_data_df['Price']
print(y)

    Size (sq. m)  No. rooms  Age (yrs)
0            102          4          2
1             67          4         29
2             74          2         27
3             63          4          1
4            114          3         12
5            109          5          9
6             73          3         21
7            108          4         24
8             69          2         29
9             81          4         11
10            60          5          9
11            62          5         32
12            87          4         19
13            61          5         15
14            62          4          9
15            69          5         21
16           119          2         24
17           101          3         21
18            76          4         20
19            91          4          7
20            75          4         19
0     190257
1     216410
2     132887
3     197341
4     127647
5     225818
6     336404
7     324823
8     313475
9     144088
10    182709

In [20]:
print(X.shape)
print(y.shape)

(21, 3)
(21,)


# 3. Initialize training

In [ ]:
"""Pseudocode:

For each pass of epoch:
    Calculate the gradient rate
    
"""

## Add a bias column (column full of 1s) into X

In [ ]:
# Create a column of ones with the same number of rows as X
bias_column = np.ones((X.shape[0], 1))

# Horizontally stack the bias column with X
X = np.hstack((bias_column, X))

In [22]:
# Display X and X.shape
display(X)
print(X.shape)

array([[  1., 102.,   4.,   2.],
       [  1.,  67.,   4.,  29.],
       [  1.,  74.,   2.,  27.],
       [  1.,  63.,   4.,   1.],
       [  1., 114.,   3.,  12.],
       [  1., 109.,   5.,   9.],
       [  1.,  73.,   3.,  21.],
       [  1., 108.,   4.,  24.],
       [  1.,  69.,   2.,  29.],
       [  1.,  81.,   4.,  11.],
       [  1.,  60.,   5.,   9.],
       [  1.,  62.,   5.,  32.],
       [  1.,  87.,   4.,  19.],
       [  1.,  61.,   5.,  15.],
       [  1.,  62.,   4.,   9.],
       [  1.,  69.,   5.,  21.],
       [  1., 119.,   2.,  24.],
       [  1., 101.,   3.,  21.],
       [  1.,  76.,   4.,  20.],
       [  1.,  91.,   4.,   7.],
       [  1.,  75.,   4.,  19.]])

(21, 4)


In [25]:
# Looping over each epoch
for epoch in range(0,epochs):
    # Calculate the gradient:
    gradient = (1/y.shape[0]) * X.transpose().dot(X.dot(theta)-y)
    print(gradient)
    
    # Update the theta:
    theta = theta - lr_rate * gradient
    print(theta)
    



[ -10036.87602518   66831.79034265  -54374.5097581  -323577.75359123]
[  40.55177305 2452.25837111  169.78219787  876.9567311 ]
[ -10007.25159916   66232.84868754  -54308.8666468  -320474.85965257]
[  41.55249821 2445.63508624  175.21308454  909.00421706]
[  -9978.07499125   65624.44299865  -54244.41050476 -317404.58640912]
[  42.5503057  2439.07264194  180.63752559  940.7446757 ]
[  -9949.21197781   65017.86519353  -54180.6446316  -314364.39368201]
[  43.5452269  2432.57085542  186.05559005  972.18111507]
[  -9920.62555204   64416.03005476  -54117.43540211 -311353.41105001]
[  44.53728946 2426.12925242  191.46733359 1003.31645618]
[  -9892.30417312   63819.6599001   -54054.74426653 -308371.20713928]
[  45.52651987 2419.74728643  196.87280802 1034.15357689]
[  -9864.24298408   63228.90352059  -53992.55759674 -305417.46744555]
[  46.51294417 2413.42439608  202.27206378 1064.69532364]
[  -9836.43889507   62643.7599613   -53930.86832206 -302491.90998003]
[  47.49658806 2407.16002008  207.